Repository MTrab/landroid_cloud, pull requests merged in 2023-04, with the labels that each got.

#315 Bumping pyworxcloud
  custom_components/landroid_cloud/manifest.json
Labels: bug

#320 Extend issue template
  .github/ISSUE_TEMPLATE/issue.yml
Labels: skip-changelog

#325 Translations update
  custom_components/landroid_cloud/translations/cs.json
  custom_components/landroid_cloud/translations/da.json
  custom_components/landroid_cloud/translations/ro_RO.json
  custom_components/landroid_cloud/translations/vacuum.cs.json
  custom_components/landroid_cloud/translations/vacuum.da.json
  custom_components/landroid_cloud/translations/vacuum.en.json
  custom_components/landroid_cloud/translations/vacuum.ro_RO.json
Labels: enhancement

#330 Fix token refresh
  custom_components/landroid_cloud/manifest.json
Labels: bug

#331 Add integration version to issue template
  .github/ISSUE_TEMPLATE/issue.yml
Labels: skip-changelog

#334 Fixing OTS call
  custom_components/landroid_cloud/device_base.py
Labels: bug

#338 Redact lat and lon from diagnostics
  custom_components/landroid_cloud/const.py
  custom_components/landroid_cloud/diagnostics.py
Labels: bug

#348 Fix broken torque service call
  custom_components/landroid_cloud/devices/worx.py
Labels: bug

#349 Fix timeout handling
  custom_components/landroid_cloud/manifest.json
Labels: bug

#353 Fix bug in party mode service.
  custom_components/landroid_cloud/device_base.py
Labels: bug

#352 Add translation_key to fix translations.
  custom_components/landroid_cloud/device_base.py
Labels: bug

#354 Updating translations to new style
  custom_components/landroid_cloud/strings.json
  custom_components/landroid_cloud/strings.vacuum.json
  custom_components/landroid_cloud/translations/cs.json
  custom_components/landroid_cloud/translations/da.json
  custom_components/landroid_cloud/translations/de.json
  custom_components/landroid_cloud/translations/en.json
  custom_components/landroid_cloud/translations/es.json
  custom_components/landroid_cloud/translations/fr.json
  custom_components/landroid_cloud/translations/it.json
  custom_components/landroid_cloud/translations/nb.json
  custom_components/landroid_cloud/translations/nl.json
  custom_components/landroid_cloud/translations/no.json
  custom_components/landroid_cloud/translations/pl.json
  custom_components/landroid_cloud/translations/ro_RO.json
  custom_components/landroid_cloud/translations/ru.json
  custom_components/landroid_cloud/translations/sv.json
  custom_components/landroid_cloud/translations/vacuum.cs.json
  custom_components/landroid_cloud/translations/vacuum.da.json
  custom_components/landroid_cloud/translations/vacuum.de.json
  custom_components/landroid_cloud/translations/vacuum.en.json
  custom_components/landroid_cloud/translations/vacuum.es.json
  custom_components/landroid_cloud/translations/vacuum.fr.json
  custom_components/landroid_cloud/translations/vacuum.it.json
  custom_components/landroid_cloud/translations/vacuum.nb.json
  custom_components/landroid_cloud/translations/vacuum.nl.json
  custom_components/landroid_cloud/translations/vacuum.no.json
  custom_components/landroid_cloud/translations/vacuum.pl.json
  custom_components/landroid_cloud/translations/vacuum.ro_RO.json
  custom_components/landroid_cloud/translations/vacuum.ru.json
  custom_components/landroid_cloud/translations/vacuum.sv.json
Labels: bug
