Repository MTrab/landroid_cloud, pull requests merged in 2024-05, with the labels that each got.

#598 Fix NoneType value for blade.reset_at property
  custom_components/landroid_cloud/sensor.py
Labels: bug, patch

#606 Switch to enum.StrEnum
  custom_components/landroid_cloud/utils/logger.py
Labels: bug, patch

#607 Disable torque entity due to error
  custom_components/landroid_cloud/number.py
Labels: bug, patch

#610 Translations update and adding Estonian language
  custom_components/landroid_cloud/translations/cs.json
  custom_components/landroid_cloud/translations/da.json
  custom_components/landroid_cloud/translations/de.json
  custom_components/landroid_cloud/translations/en.json
  custom_components/landroid_cloud/translations/es.json
  custom_components/landroid_cloud/translations/et.json
  custom_components/landroid_cloud/translations/fr.json
  custom_components/landroid_cloud/translations/fr_FR.json
  custom_components/landroid_cloud/translations/it.json
  custom_components/landroid_cloud/translations/nb.json
  custom_components/landroid_cloud/translations/nl.json
  custom_components/landroid_cloud/translations/no.json
  custom_components/landroid_cloud/translations/pl.json
  custom_components/landroid_cloud/translations/ro_RO.json
  custom_components/landroid_cloud/translations/ru.json
  custom_components/landroid_cloud/translations/sv.json
Labels: translation, patch

#624 Delete INFO.md
  INFO.md
Labels: patch

#626 Add missing translations to base language (EN)
  custom_components/landroid_cloud/translations/en.json
Labels: enhancement, translation, patch

#629 Multiple translation updates
  custom_components/landroid_cloud/translations/da.json
  custom_components/landroid_cloud/translations/en.json
  custom_components/landroid_cloud/translations/et.json
  custom_components/landroid_cloud/translations/fr_FR.json
  custom_components/landroid_cloud/translations/it.json
  custom_components/landroid_cloud/translations/nl.json
  custom_components/landroid_cloud/translations/pl.json
  custom_components/landroid_cloud/translations/sv.json
Labels: translation, patch

#625 Change minimum OTS run-time
  custom_components/landroid_cloud/services.yaml
Labels: bug, patch

#627 Bump pyworxcloud to fix zoning issues
  custom_components/landroid_cloud/manifest.json
Labels: bug, dependencies, patch
