Repository MTrab/landroid_cloud, pull requests merged in 2025-02, with the labels that each got.

#724 Update worktime_total sensor
  custom_components/landroid_cloud/sensor.py
Labels: patch

#753 Update devcontainer
  .devcontainer.json
  .vscode/settings.json
Labels: dependencies, patch, skip-changelog

#759 Reenable torque entity
  custom_components/landroid_cloud/number.py
Labels: enhancement, patch

#758 Fix online indicator
  config/configuration.yaml
  custom_components/landroid_cloud/api.py
  custom_components/landroid_cloud/button.py
  custom_components/landroid_cloud/device_base.py
  custom_components/landroid_cloud/sensor.py
Labels: bug, patch

#760 Update release-drafter template
  .github/release-drafter.yml
Labels: patch, skip-changelog

#762 Update language: DE
  custom_components/landroid_cloud/translations/de.json
Labels: translation, patch

#766 Bump pyworxcloud to fix v2025.3 dependencies
  .devcontainer.json
  .ruff.toml
  custom_components/landroid_cloud/__init__.py
  custom_components/landroid_cloud/api.py
  custom_components/landroid_cloud/binary_sensor.py
  custom_components/landroid_cloud/config_flow.py
  custom_components/landroid_cloud/const.py
  custom_components/landroid_cloud/device_base.py
  custom_components/landroid_cloud/devices/ferrex.py
  custom_components/landroid_cloud/devices/kress.py
  custom_components/landroid_cloud/devices/landxcape.py
  custom_components/landroid_cloud/devices/worx.py
  custom_components/landroid_cloud/lawn_mower.py
  custom_components/landroid_cloud/manifest.json
  custom_components/landroid_cloud/sensor.py
  custom_components/landroid_cloud/services.py
  custom_components/landroid_cloud/utils/logger.py
  requirements.txt
Labels: dependencies, patch
